/*
 * NOTICE: Do not manually edit this file. It has been autogenerated by
 * protocol/parse.py. Any changes should me made there, instead of here.
 */
#pragma once
#include <net/packet.h>
#include <boost/cstdint.hpp>
#include <net/PacketParameters.h>

namespace packet {
namespace protocol {

// Request Server Info
class Admin_RequestServerInfo : public Packet
{
private:
	packet::MUID uidAdmin;

public:
	enum { packetID = 505 };

	Admin_RequestServerInfo(packet::MUID uidAdmin);

	const char* name() const;
	const char* doc() const;
	boost::uint16_t id() const;
	Buffer serialize() const;
};

}
}