/*
 * NOTICE: Do not manually edit this file. It has been autogenerated by
 * protocol/parse.py. Any changes should me made there, instead of here.
 */
#pragma once
#include <net/packet.h>
#include <boost/cstdint.hpp>
#include <net/PacketParameters.h>

namespace packet {
namespace protocol {

// Halt Server
class Admin_Halt : public Packet
{
private:
	packet::MUID uidAdmin;

public:
	enum { packetID = 511 };

	Admin_Halt(packet::MUID uidAdmin);

	const char* name() const;
	const char* doc() const;
	boost::uint16_t id() const;
	Buffer serialize() const;

	virtual ~Admin_Halt()
	{
	}

};

}
}