/*
 * NOTICE: Do not manually edit this file. It has been autogenerated by
 * protocol/parse.py. Any changes should me made there, instead of here.
 */
#pragma once
#include <net/packet.h>
#include <boost/cstdint.hpp>
#include <net/PacketParameters.h>

namespace packet {
namespace protocol {

// Response Server Info
class Admin_ResponseServerInfo : public Packet
{
private:
	packet::blob ServerInfo;

public:
	enum { packetID = 506 };

	Admin_ResponseServerInfo(packet::blob ServerInfo);

	const char* name() const;
	const char* doc() const;
	boost::uint16_t id() const;
	Buffer serialize() const;

	virtual ~Admin_ResponseServerInfo()
	{
	}

};

}
}