/*
 * NOTICE: Do not manually edit this file. It has been autogenerated by
 * protocol/parse.py. Any changes should me made there, instead of here.
 */
#pragma once
#include <net/packet.h>
#include <boost/cstdint.hpp>
#include <net/PacketParameters.h>

namespace packet {
namespace protocol {

// Allow Tunneling by TCP
class Agent_AllowTunnelingTCP : public Packet
{

public:
	enum { packetID = 5083 };

	Agent_AllowTunnelingTCP();

	const char* name() const;
	const char* doc() const;
	boost::uint16_t id() const;
	Buffer serialize() const;

	virtual ~Agent_AllowTunnelingTCP()
	{
	}

};

}
}