/*
 * NOTICE: Do not manually edit this file. It has been autogenerated by
 * protocol/parse.py. Any changes should me made there, instead of here.
 */
#pragma once
#include <net/packet.h>
#include <boost/cstdint.hpp>
#include <net/PacketParameters.h>

namespace packet {
namespace protocol {

// Unbind Client from Peer
class Agent_PeerUnbind : public Packet
{
private:
	packet::MUID CharUID;

public:
	enum { packetID = 5073 };

	Agent_PeerUnbind(packet::MUID CharUID);

	const char* name() const;
	const char* doc() const;
	boost::uint16_t id() const;
	Buffer serialize() const;
};

}
}