/*
 * NOTICE: Do not manually edit this file. It has been autogenerated by
 * protocol/parse.py. Any changes should me made there, instead of here.
 */
#pragma once
#include <net/packet.h>
#include <boost/cstdint.hpp>
#include <net/PacketParameters.h>

namespace packet {
namespace protocol {

// send announce of scheduler.
class Announce_Schedule : public Packet
{
private:
	packet::string strAnnounce;

public:
	enum { packetID = 7002 };

	Announce_Schedule(packet::string strAnnounce);

	const char* name() const;
	const char* doc() const;
	boost::uint16_t id() const;
	Buffer serialize() const;
};

}
}