/*
 * NOTICE: Do not manually edit this file. It has been autogenerated by
 * protocol/parse.py. Any changes should me made there, instead of here.
 */
#pragma once
#include <net/packet.h>
#include <boost/cstdint.hpp>
#include <net/PacketParameters.h>

namespace packet {
namespace protocol {

// Request Channel All Player List
class Channel_RequestAllPlayerList : public Packet
{
private:
	packet::MUID uidPlayer;
	packet::MUID uidChannel;
	packet::uint32 PlaceFilter;
	packet::uint32 Options;

public:
	enum { packetID = 1232 };

	Channel_RequestAllPlayerList(packet::MUID uidPlayer, packet::MUID uidChannel, packet::uint32 PlaceFilter, packet::uint32 Options);

	const char* name() const;
	const char* doc() const;
	boost::uint16_t id() const;
	Buffer serialize() const;

	virtual ~Channel_RequestAllPlayerList()
	{
	}

};

}
}