/*
 * NOTICE: Do not manually edit this file. It has been autogenerated by
 * protocol/parse.py. Any changes should me made there, instead of here.
 */
#pragma once
#include <net/packet.h>
#include <boost/cstdint.hpp>
#include <net/PacketParameters.h>

namespace packet {
namespace protocol {

// Create a ChatRoom
class ChatRoom_Create : public Packet
{
private:
	packet::MUID uidPlayer;
	packet::string ChatRoomName;

public:
	enum { packetID = 1651 };

	ChatRoom_Create(packet::MUID uidPlayer, packet::string ChatRoomName);

	const char* name() const;
	const char* doc() const;
	boost::uint16_t id() const;
	Buffer serialize() const;

	virtual ~ChatRoom_Create()
	{
	}

};

}
}