/*
 * NOTICE: Do not manually edit this file. It has been autogenerated by
 * protocol/parse.py. Any changes should me made there, instead of here.
 */
#pragma once
#include <net/packet.h>
#include <boost/cstdint.hpp>
#include <net/PacketParameters.h>

namespace packet {
namespace protocol {

// Synchronize Clock
class Clock_Synchronize : public Packet
{
private:
	packet::uint32 GlobalClock_msec;

public:
	enum { packetID = 361 };

	Clock_Synchronize(packet::uint32 GlobalClock_msec);

	const char* name() const;
	const char* doc() const;
	boost::uint16_t id() const;
	Buffer serialize() const;

	virtual ~Clock_Synchronize()
	{
	}

};

}
}