/*
 * NOTICE: Do not manually edit this file. It has been autogenerated by
 * protocol/parse.py. Any changes should me made there, instead of here.
 */
#pragma once
#include <net/packet.h>
#include <boost/cstdint.hpp>
#include <net/PacketParameters.h>

namespace packet {
namespace protocol {

// Game.Dead
class Game_Dead : public Packet
{
private:
	packet::MUID Attacker;
	packet::uint32 AttackerArg;
	packet::MUID Victim;
	packet::uint32 VictimArg;

public:
	enum { packetID = 1512 };

	Game_Dead(packet::MUID Attacker, packet::uint32 AttackerArg, packet::MUID Victim, packet::uint32 VictimArg);

	const char* name() const;
	const char* doc() const;
	boost::uint16_t id() const;
	Buffer serialize() const;
};

}
}