/*
 * NOTICE: Do not manually edit this file. It has been autogenerated by
 * protocol/parse.py. Any changes should me made there, instead of here.
 */
#pragma once
#include <net/packet.h>
#include <boost/cstdint.hpp>
#include <net/PacketParameters.h>

namespace packet {
namespace protocol {

// Game.LevelDown
class Game_LevelDown : public Packet
{
private:
	packet::MUID Player;
	packet::int32 Level;

public:
	enum { packetID = 1514 };

	Game_LevelDown(packet::MUID Player, packet::int32 Level);

	const char* name() const;
	const char* doc() const;
	boost::uint16_t id() const;
	Buffer serialize() const;

	virtual ~Game_LevelDown()
	{
	}

};

}
}