/*
 * NOTICE: Do not manually edit this file. It has been autogenerated by
 * protocol/parse.py. Any changes should me made there, instead of here.
 */
#pragma once
#include <net/packet.h>
#include <boost/cstdint.hpp>
#include <net/PacketParameters.h>

namespace packet {
namespace protocol {

// Response TimeSync for Game
class Game_ResponseTimeSync : public Packet
{
private:
	packet::uint32 LocalTimeStamp;
	packet::uint32 GlobalTimeStamp;

public:
	enum { packetID = 1522 };

	Game_ResponseTimeSync(packet::uint32 LocalTimeStamp, packet::uint32 GlobalTimeStamp);

	const char* name() const;
	const char* doc() const;
	boost::uint16_t id() const;
	Buffer serialize() const;
};

}
}