/*
 * NOTICE: Do not manually edit this file. It has been autogenerated by
 * protocol/parse.py. Any changes should me made there, instead of here.
 */
#pragma once
#include <net/packet.h>
#include <boost/cstdint.hpp>
#include <net/PacketParameters.h>

namespace packet {
namespace protocol {

// Ping
class HShield_Ping : public Packet
{
private:
	packet::uint32 TimeStamp;
	packet::blob CRCInfo;

public:
	enum { packetID = 324 };

	HShield_Ping(packet::uint32 TimeStamp, packet::blob CRCInfo);

	const char* name() const;
	const char* doc() const;
	boost::uint16_t id() const;
	Buffer serialize() const;

	virtual ~HShield_Ping()
	{
	}

};

}
}