/*
 * NOTICE: Do not manually edit this file. It has been autogenerated by
 * protocol/parse.py. Any changes should me made there, instead of here.
 */
#pragma once
#include <net/packet.h>
#include <boost/cstdint.hpp>
#include <net/PacketParameters.h>

namespace packet {
namespace protocol {

// Local Login
class Local_Login : public Packet
{
private:
	packet::MUID uidComm;
	packet::MUID uidPlayer;

public:
	enum { packetID = 203 };

	Local_Login(packet::MUID uidComm, packet::MUID uidPlayer);

	const char* name() const;
	const char* doc() const;
	boost::uint16_t id() const;
	Buffer serialize() const;

	virtual ~Local_Login()
	{
	}

};

}
}