/*
 * NOTICE: Do not manually edit this file. It has been autogenerated by
 * protocol/parse.py. Any changes should me made there, instead of here.
 */
#pragma once
#include <net/packet.h>
#include <boost/cstdint.hpp>
#include <net/PacketParameters.h>

namespace packet {
namespace protocol {

// Remove a Friend
class Match_Friend_Remove : public Packet
{
private:
	packet::string Name;

public:
	enum { packetID = 1902 };

	Match_Friend_Remove(packet::string Name);

	const char* name() const;
	const char* doc() const;
	boost::uint16_t id() const;
	Buffer serialize() const;

	virtual ~Match_Friend_Remove()
	{
	}

};

}
}