/*
 * NOTICE: Do not manually edit this file. It has been autogenerated by
 * protocol/parse.py. Any changes should me made there, instead of here.
 */
#pragma once
#include <net/packet.h>
#include <boost/cstdint.hpp>
#include <net/PacketParameters.h>

namespace packet {
namespace protocol {

// Standby Clan List
class Match_Clan_Standby_ClanList : public Packet
{
private:
	packet::int32 PrevClanListCount;
	packet::int32 NextClanListCount;
	packet::blob ClanList;

public:
	enum { packetID = 2027 };

	Match_Clan_Standby_ClanList(packet::int32 PrevClanListCount, packet::int32 NextClanListCount, packet::blob ClanList);

	const char* name() const;
	const char* doc() const;
	boost::uint16_t id() const;
	Buffer serialize() const;
};

}
}