/*
 * NOTICE: Do not manually edit this file. It has been autogenerated by
 * protocol/parse.py. Any changes should me made there, instead of here.
 */
#pragma once
#include <net/packet.h>
#include <boost/cstdint.hpp>
#include <net/PacketParameters.h>

namespace packet {
namespace protocol {

// Request Close Clan
class Match_Clan_RequestCloseClan : public Packet
{
private:
	packet::MUID uidChar;
	packet::string ClanName;

public:
	enum { packetID = 2006 };

	Match_Clan_RequestCloseClan(packet::MUID uidChar, packet::string ClanName);

	const char* name() const;
	const char* doc() const;
	boost::uint16_t id() const;
	Buffer serialize() const;

	virtual ~Match_Clan_RequestCloseClan()
	{
	}

};

}
}