/*
 * NOTICE: Do not manually edit this file. It has been autogenerated by
 * protocol/parse.py. Any changes should me made there, instead of here.
 */
#pragma once
#include <net/packet.h>
#include <boost/cstdint.hpp>
#include <net/PacketParameters.h>

namespace packet {
namespace protocol {

// Response EmblemURL
class Match_Clan_Response_EmblemURL : public Packet
{
private:
	packet::int32 ClanCLID;
	packet::int32 EmblemChecksum;
	packet::string EmblemURL;

public:
	enum { packetID = 2052 };

	Match_Clan_Response_EmblemURL(packet::int32 ClanCLID, packet::int32 EmblemChecksum, packet::string EmblemURL);

	const char* name() const;
	const char* doc() const;
	boost::uint16_t id() const;
	Buffer serialize() const;

	virtual ~Match_Clan_Response_EmblemURL()
	{
	}

};

}
}