/*
 * NOTICE: Do not manually edit this file. It has been autogenerated by
 * protocol/parse.py. Any changes should me made there, instead of here.
 */
#pragma once
#include <net/packet.h>
#include <boost/cstdint.hpp>
#include <net/PacketParameters.h>

namespace packet {
namespace protocol {

// Response Item Gamble Result Item
class Match_GambleResultItem : public Packet
{
private:
	packet::uint32 ItemID;
	packet::uint32 RentHourPeriodTimes60;

public:
	enum { packetID = 1842 };

	Match_GambleResultItem(packet::uint32 ItemID, packet::uint32 RentHourPeriodTimes60);

	const char* name() const;
	const char* doc() const;
	boost::uint16_t id() const;
	Buffer serialize() const;

	virtual ~Match_GambleResultItem()
	{
	}

};

}
}