/*
 * NOTICE: Do not manually edit this file. It has been autogenerated by
 * protocol/parse.py. Any changes should me made there, instead of here.
 */
#pragma once
#include <net/packet.h>
#include <boost/cstdint.hpp>
#include <net/PacketParameters.h>

namespace packet {
namespace protocol {

// Response My Simple CharInfo
class Match_ResponseMySimpleCharInfo : public Packet
{
private:
	packet::blob MySimpleCharInfo;

public:
	enum { packetID = 1804 };

	Match_ResponseMySimpleCharInfo(packet::blob MySimpleCharInfo);

	const char* name() const;
	const char* doc() const;
	boost::uint16_t id() const;
	Buffer serialize() const;
};

}
}