/*
 * NOTICE: Do not manually edit this file. It has been autogenerated by
 * protocol/parse.py. Any changes should me made there, instead of here.
 */
#pragma once
#include <net/packet.h>
#include <boost/cstdint.hpp>
#include <net/PacketParameters.h>

namespace packet {
namespace protocol {

// Login Failed from DBAgent
class Match_LoginFailedFromDBAgent : public Packet
{
private:
	packet::MUID CommUID;
	packet::int32 Result;

public:
	enum { packetID = 1008 };

	Match_LoginFailedFromDBAgent(packet::MUID CommUID, packet::int32 Result);

	const char* name() const;
	const char* doc() const;
	boost::uint16_t id() const;
	Buffer serialize() const;
};

}
}