/*
 * NOTICE: Do not manually edit this file. It has been autogenerated by
 * protocol/parse.py. Any changes should me made there, instead of here.
 */
#pragma once
#include <net/packet.h>
#include <boost/cstdint.hpp>
#include <net/PacketParameters.h>

namespace packet {
namespace protocol {

// Request Clan Msg
class Match_Clan_Request_Msg : public Packet
{
private:
	packet::MUID uidSender;
	packet::string Msg;

public:
	enum { packetID = 2021 };

	Match_Clan_Request_Msg(packet::MUID uidSender, packet::string Msg);

	const char* name() const;
	const char* doc() const;
	boost::uint16_t id() const;
	Buffer serialize() const;
};

}
}