/*
 * NOTICE: Do not manually edit this file. It has been autogenerated by
 * protocol/parse.py. Any changes should me made there, instead of here.
 */
#pragma once
#include <net/packet.h>
#include <boost/cstdint.hpp>
#include <net/PacketParameters.h>

namespace packet {
namespace protocol {

// Request Agreed Join Clan
class Match_Clan_RequestAgreedJoinClan : public Packet
{
private:
	packet::MUID uidClanAdmin;
	packet::string ClanName;
	packet::string szJoiner;

public:
	enum { packetID = 2012 };

	Match_Clan_RequestAgreedJoinClan(packet::MUID uidClanAdmin, packet::string ClanName, packet::string szJoiner);

	const char* name() const;
	const char* doc() const;
	boost::uint16_t id() const;
	Buffer serialize() const;
};

}
}