/*
 * NOTICE: Do not manually edit this file. It has been autogenerated by
 * protocol/parse.py. Any changes should me made there, instead of here.
 */
#pragma once
#include <net/packet.h>
#include <boost/cstdint.hpp>
#include <net/PacketParameters.h>

namespace packet {
namespace protocol {

// Request Create Clan
class Match_Clan_RequestCreateClan : public Packet
{
private:
	packet::MUID uidChar;
	packet::int32 RequestID;
	packet::string ClanName;
	packet::string Member1CharName;
	packet::string Member2CharName;
	packet::string Member3CharName;
	packet::string Member4CharName;

public:
	enum { packetID = 2000 };

	Match_Clan_RequestCreateClan(packet::MUID uidChar, packet::int32 RequestID, packet::string ClanName, packet::string Member1CharName, packet::string Member2CharName, packet::string Member3CharName, packet::string Member4CharName);

	const char* name() const;
	const char* doc() const;
	boost::uint16_t id() const;
	Buffer serialize() const;
};

}
}