/*
 * NOTICE: Do not manually edit this file. It has been autogenerated by
 * protocol/parse.py. Any changes should me made there, instead of here.
 */
#pragma once
#include <net/packet.h>
#include <boost/cstdint.hpp>
#include <net/PacketParameters.h>

namespace packet {
namespace protocol {

// Response List Friend
class Match_Response_FriendList : public Packet
{
private:
	packet::blob FriendList;

public:
	enum { packetID = 1904 };

	Match_Response_FriendList(packet::blob FriendList);

	const char* name() const;
	const char* doc() const;
	boost::uint16_t id() const;
	Buffer serialize() const;

	virtual ~Match_Response_FriendList()
	{
	}

};

}
}