/*
 * NOTICE: Do not manually edit this file. It has been autogenerated by
 * protocol/parse.py. Any changes should me made there, instead of here.
 */
#pragma once
#include <net/packet.h>
#include <boost/cstdint.hpp>
#include <net/PacketParameters.h>

namespace packet {
namespace protocol {

// Notify Message
class Match_Notify : public Packet
{
private:
	packet::uint32 nMsgID;

public:
	enum { packetID = 401 };

	Match_Notify(packet::uint32 nMsgID);

	const char* name() const;
	const char* doc() const;
	boost::uint16_t id() const;
	Buffer serialize() const;

	virtual ~Match_Notify()
	{
	}

};

}
}