/*
 * NOTICE: Do not manually edit this file. It has been autogenerated by
 * protocol/parse.py. Any changes should me made there, instead of here.
 */
#pragma once
#include <net/packet.h>
#include <boost/cstdint.hpp>
#include <net/PacketParameters.h>

namespace packet {
namespace protocol {

// Request Account Item List
class Match_RequestAccountItemList : public Packet
{
private:
	packet::MUID uid;

public:
	enum { packetID = 1831 };

	Match_RequestAccountItemList(packet::MUID uid);

	const char* name() const;
	const char* doc() const;
	boost::uint16_t id() const;
	Buffer serialize() const;

	virtual ~Match_RequestAccountItemList()
	{
	}

};

}
}