/*
 * NOTICE: Do not manually edit this file. It has been autogenerated by
 * protocol/parse.py. Any changes should me made there, instead of here.
 */
#pragma once
#include <net/packet.h>
#include <boost/cstdint.hpp>
#include <net/PacketParameters.h>

namespace packet {
namespace protocol {

// Login from Netmarble Japan
class Match_LoginNetmarbleJP : public Packet
{
private:
	packet::string LoginID;
	packet::string LoginPW;
	packet::int32 CommandVersion;
	packet::uint32 nChecksumPack;

public:
	enum { packetID = 1004 };

	Match_LoginNetmarbleJP(packet::string LoginID, packet::string LoginPW, packet::int32 CommandVersion, packet::uint32 nChecksumPack);

	const char* name() const;
	const char* doc() const;
	boost::uint16_t id() const;
	Buffer serialize() const;

	virtual ~Match_LoginNetmarbleJP()
	{
	}

};

}
}