/*
 * NOTICE: Do not manually edit this file. It has been autogenerated by
 * protocol/parse.py. Any changes should me made there, instead of here.
 */
#pragma once
#include <net/packet.h>
#include <boost/cstdint.hpp>
#include <net/PacketParameters.h>

namespace packet {
namespace protocol {

// Response Simple CharInfo
class Match_ResponseSimpleCharInfo : public Packet
{
private:
	packet::MUID uid;
	packet::blob SimpleCharInfo;

public:
	enum { packetID = 1802 };

	Match_ResponseSimpleCharInfo(packet::MUID uid, packet::blob SimpleCharInfo);

	const char* name() const;
	const char* doc() const;
	boost::uint16_t id() const;
	Buffer serialize() const;

	virtual ~Match_ResponseSimpleCharInfo()
	{
	}

};

}
}