/*
 * NOTICE: Do not manually edit this file. It has been autogenerated by
 * protocol/parse.py. Any changes should me made there, instead of here.
 */
#pragma once
#include <net/packet.h>
#include <boost/cstdint.hpp>
#include <net/PacketParameters.h>

namespace packet {
namespace protocol {

// Response Clan Info
class Match_Clan_Response_Clan_Info : public Packet
{
private:
	packet::blob ClanInfo;

public:
	enum { packetID = 2026 };

	Match_Clan_Response_Clan_Info(packet::blob ClanInfo);

	const char* name() const;
	const char* doc() const;
	boost::uint16_t id() const;
	Buffer serialize() const;
};

}
}