/*
 * NOTICE: Do not manually edit this file. It has been autogenerated by
 * protocol/parse.py. Any changes should me made there, instead of here.
 */
#pragma once
#include <net/packet.h>
#include <boost/cstdint.hpp>
#include <net/PacketParameters.h>

namespace packet {
namespace protocol {

// Answer Join Agreement
class Match_Clan_AnswerJoinAgreement : public Packet
{
private:
	packet::MUID uidClanAdmin;
	packet::string JoinerCharName;
	packet::boolean Answer;

public:
	enum { packetID = 2011 };

	Match_Clan_AnswerJoinAgreement(packet::MUID uidClanAdmin, packet::string JoinerCharName, packet::boolean Answer);

	const char* name() const;
	const char* doc() const;
	boost::uint16_t id() const;
	Buffer serialize() const;

	virtual ~Match_Clan_AnswerJoinAgreement()
	{
	}

};

}
}