/*
 * NOTICE: Do not manually edit this file. It has been autogenerated by
 * protocol/parse.py. Any changes should me made there, instead of here.
 */
#pragma once
#include <net/packet.h>
#include <boost/cstdint.hpp>
#include <net/PacketParameters.h>

namespace packet {
namespace protocol {

// Response Clan Member List
class Match_Clan_Response_ClanMemberList : public Packet
{
private:
	packet::blob ClanMemberList;

public:
	enum { packetID = 2024 };

	Match_Clan_Response_ClanMemberList(packet::blob ClanMemberList);

	const char* name() const;
	const char* doc() const;
	boost::uint16_t id() const;
	Buffer serialize() const;
};

}
}