/*
 * NOTICE: Do not manually edit this file. It has been autogenerated by
 * protocol/parse.py. Any changes should me made there, instead of here.
 */
#pragma once
#include <net/packet.h>
#include <boost/cstdint.hpp>
#include <net/PacketParameters.h>

namespace packet {
namespace protocol {

// Register Agent to MatchServer
class Match_RegisterAgent : public Packet
{
private:
	packet::string Address;
	packet::int32 Port;
	packet::int32 UDPPort;

public:
	enum { packetID = 5001 };

	Match_RegisterAgent(packet::string Address, packet::int32 Port, packet::int32 UDPPort);

	const char* name() const;
	const char* doc() const;
	boost::uint16_t id() const;
	Buffer serialize() const;

	virtual ~Match_RegisterAgent()
	{
	}

};

}
}