/*
 * NOTICE: Do not manually edit this file. It has been autogenerated by
 * protocol/parse.py. Any changes should me made there, instead of here.
 */
#pragma once
#include <net/packet.h>
#include <boost/cstdint.hpp>
#include <net/PacketParameters.h>

namespace packet {
namespace protocol {

// Request Account Character Info
class Match_RequestAccountCharInfo : public Packet
{
private:
	packet::vector CharNum;
	packet::int32 _0B;

public:
	enum { packetID = 1719 };

	Match_RequestAccountCharInfo(packet::vector CharNum, packet::int32 _0B);

	const char* name() const;
	const char* doc() const;
	boost::uint16_t id() const;
	Buffer serialize() const;

	virtual ~Match_RequestAccountCharInfo()
	{
	}

};

}
}