/*
 * NOTICE: Do not manually edit this file. It has been autogenerated by
 * protocol/parse.py. Any changes should me made there, instead of here.
 */
#pragma once
#include <net/packet.h>
#include <boost/cstdint.hpp>
#include <net/PacketParameters.h>

namespace packet {
namespace protocol {

// dump gamble item info
class MC_ADMIN_DUMP_GAMBLEITEM_LOG : public Packet
{

public:
	enum { packetID = 535 };

	MC_ADMIN_DUMP_GAMBLEITEM_LOG();

	const char* name() const;
	const char* doc() const;
	boost::uint16_t id() const;
	Buffer serialize() const;

	virtual ~MC_ADMIN_DUMP_GAMBLEITEM_LOG()
	{
	}

};

}
}