/*
 * NOTICE: Do not manually edit this file. It has been autogenerated by
 * protocol/parse.py. Any changes should me made there, instead of here.
 */
#pragma once
#include <net/packet.h>
#include <boost/cstdint.hpp>
#include <net/PacketParameters.h>

namespace packet {
namespace protocol {

// update ip to country code.
class MC_LOCAL_UPDAET_IP_TO_COUNTRY : public Packet
{

public:
	enum { packetID = 50006 };

	MC_LOCAL_UPDAET_IP_TO_COUNTRY();

	const char* name() const;
	const char* doc() const;
	boost::uint16_t id() const;
	Buffer serialize() const;

	virtual ~MC_LOCAL_UPDAET_IP_TO_COUNTRY()
	{
	}

};

}
}