/*
 * NOTICE: Do not manually edit this file. It has been autogenerated by
 * protocol/parse.py. Any changes should me made there, instead of here.
 */
#pragma once
#include <net/packet.h>
#include <boost/cstdint.hpp>
#include <net/PacketParameters.h>

namespace packet {
namespace protocol {

// update accept invalid ip.
class MC_LOCAL_UPDATE_ACCEPT_INVALID_IP : public Packet
{

public:
	enum { packetID = 50009 };

	MC_LOCAL_UPDATE_ACCEPT_INVALID_IP();

	const char* name() const;
	const char* doc() const;
	boost::uint16_t id() const;
	Buffer serialize() const;
};

}
}