/*
 * NOTICE: Do not manually edit this file. It has been autogenerated by
 * protocol/parse.py. Any changes should me made there, instead of here.
 */
#pragma once
#include <net/packet.h>
#include <boost/cstdint.hpp>
#include <net/PacketParameters.h>

namespace packet {
namespace protocol {

// update block country code.
class MC_LOCAL_UPDAET_BLOCK_COUTRYCODE : public Packet
{

public:
	enum { packetID = 50007 };

	MC_LOCAL_UPDAET_BLOCK_COUTRYCODE();

	const char* name() const;
	const char* doc() const;
	boost::uint16_t id() const;
	Buffer serialize() const;
};

}
}