/*
 * NOTICE: Do not manually edit this file. It has been autogenerated by
 * protocol/parse.py. Any changes should me made there, instead of here.
 */
#pragma once
#include <net/packet.h>
#include <boost/cstdint.hpp>
#include <net/PacketParameters.h>

namespace packet {
namespace protocol {

// get db block country code.
class MC_LOCAL_GET_DB_BLOCK_COUNTRY_CODE : public Packet
{

public:
	enum { packetID = 50004 };

	MC_LOCAL_GET_DB_BLOCK_COUNTRY_CODE();

	const char* name() const;
	const char* doc() const;
	boost::uint16_t id() const;
	Buffer serialize() const;

	virtual ~MC_LOCAL_GET_DB_BLOCK_COUNTRY_CODE()
	{
	}

};

}
}