/*
 * NOTICE: Do not manually edit this file. It has been autogenerated by
 * protocol/parse.py. Any changes should me made there, instead of here.
 */
#pragma once
#include <net/packet.h>
#include <boost/cstdint.hpp>
#include <net/PacketParameters.h>

namespace packet {
namespace protocol {

// connect
class MC_RESPONSE_KEEPER_MANAGER_CONNECT : public Packet
{
private:
	packet::MUID KeeperManagerUID;

public:
	enum { packetID = 31006 };

	MC_RESPONSE_KEEPER_MANAGER_CONNECT(packet::MUID KeeperManagerUID);

	const char* name() const;
	const char* doc() const;
	boost::uint16_t id() const;
	Buffer serialize() const;
};

}
}