/*
 * NOTICE: Do not manually edit this file. It has been autogenerated by
 * protocol/parse.py. Any changes should me made there, instead of here.
 */
#pragma once
#include <net/packet.h>
#include <boost/cstdint.hpp>
#include <net/PacketParameters.h>

namespace packet {
namespace protocol {

// 4
class MC_RESPONSE_KEEPER_ADD_HASHMAP : public Packet
{
private:
	packet::boolean result;

public:
	enum { packetID = 31034 };

	MC_RESPONSE_KEEPER_ADD_HASHMAP(packet::boolean result);

	const char* name() const;
	const char* doc() const;
	boost::uint16_t id() const;
	Buffer serialize() const;

	virtual ~MC_RESPONSE_KEEPER_ADD_HASHMAP()
	{
	}

};

}
}