/*
 * NOTICE: Do not manually edit this file. It has been autogenerated by
 * protocol/parse.py. Any changes should me made there, instead of here.
 */
#pragma once
#include <net/packet.h>
#include <boost/cstdint.hpp>
#include <net/PacketParameters.h>

namespace packet {
namespace protocol {

// response keeper connect to match server
class MC_RESPONSE_KEEPER_CONNECT_MATCHSERVER : public Packet
{
private:
	packet::MUID uid;

public:
	enum { packetID = 31012 };

	MC_RESPONSE_KEEPER_CONNECT_MATCHSERVER(packet::MUID uid);

	const char* name() const;
	const char* doc() const;
	boost::uint16_t id() const;
	Buffer serialize() const;

	virtual ~MC_RESPONSE_KEEPER_CONNECT_MATCHSERVER()
	{
	}

};

}
}