/*
 * NOTICE: Do not manually edit this file. It has been autogenerated by
 * protocol/parse.py. Any changes should me made there, instead of here.
 */
#pragma once
#include <net/packet.h>
#include <boost/cstdint.hpp>
#include <net/PacketParameters.h>

namespace packet {
namespace protocol {

// response config state
class MC_RESPONSE_CONFIG_STATE : public Packet
{
private:
	packet::int32 serverconfig;
	packet::int32 agentconfig;
	packet::int32 downloadconfig;
	packet::int32 prepareconfig;
	packet::int32 patchconfig;

public:
	enum { packetID = 31017 };

	MC_RESPONSE_CONFIG_STATE(packet::int32 serverconfig, packet::int32 agentconfig, packet::int32 downloadconfig, packet::int32 prepareconfig, packet::int32 patchconfig);

	const char* name() const;
	const char* doc() const;
	boost::uint16_t id() const;
	Buffer serialize() const;
};

}
}