/*
 * NOTICE: Do not manually edit this file. It has been autogenerated by
 * protocol/parse.py. Any changes should me made there, instead of here.
 */
#pragma once
#include <net/packet.h>
#include <boost/cstdint.hpp>
#include <net/PacketParameters.h>

namespace packet {
namespace protocol {

// requet new gameguard auth
class MC_REQUEST_GAMEGUARD_AUTH_VALUE : public Packet
{
private:
	packet::uint32 index;
	packet::uint32 value1;
	packet::uint32 value2;
	packet::uint32 value3;

public:
	enum { packetID = 9003 };

	MC_REQUEST_GAMEGUARD_AUTH_VALUE(packet::uint32 index, packet::uint32 value1, packet::uint32 value2, packet::uint32 value3);

	const char* name() const;
	const char* doc() const;
	boost::uint16_t id() const;
	Buffer serialize() const;
};

}
}