/*
 * NOTICE: Do not manually edit this file. It has been autogenerated by
 * protocol/parse.py. Any changes should me made there, instead of here.
 */
#pragma once
#include <net/packet.h>
#include <boost/cstdint.hpp>
#include <net/PacketParameters.h>

namespace packet {
namespace protocol {

// response keeper manager schedule
class MC_RESPONSE_KEEPER_MANAGER_SCHEDULE : public Packet
{
private:
	packet::int32 commandtype;
	packet::vector result;

public:
	enum { packetID = 34002 };

	MC_RESPONSE_KEEPER_MANAGER_SCHEDULE(packet::int32 commandtype, packet::vector result);

	const char* name() const;
	const char* doc() const;
	boost::uint16_t id() const;
	Buffer serialize() const;
};

}
}