/*
 * NOTICE: Do not manually edit this file. It has been autogenerated by
 * protocol/parse.py. Any changes should me made there, instead of here.
 */
#pragma once
#include <net/packet.h>
#include <boost/cstdint.hpp>
#include <net/PacketParameters.h>

namespace packet {
namespace protocol {

// MC_RESPONSE_RESOURCE_CRC32
class MC_RESPONSE_RESOURCE_CRC32 : public Packet
{
private:
	packet::uint32 crc32;

public:
	enum { packetID = 12002 };

	MC_RESPONSE_RESOURCE_CRC32(packet::uint32 crc32);

	const char* name() const;
	const char* doc() const;
	boost::uint16_t id() const;
	Buffer serialize() const;
};

}
}