/*
 * NOTICE: Do not manually edit this file. It has been autogenerated by
 * protocol/parse.py. Any changes should me made there, instead of here.
 */
#pragma once
#include <net/packet.h>
#include <boost/cstdint.hpp>
#include <net/PacketParameters.h>

namespace packet {
namespace protocol {

// keeper manager send to keeper request server reload server.ini file.
class MC_REQUEST_KEEPER_RELOAD_SERVER_CONFIG : public Packet
{
private:
	packet::string filelist;

public:
	enum { packetID = 31031 };

	MC_REQUEST_KEEPER_RELOAD_SERVER_CONFIG(packet::string filelist);

	const char* name() const;
	const char* doc() const;
	boost::uint16_t id() const;
	Buffer serialize() const;
};

}
}