/*
 * NOTICE: Do not manually edit this file. It has been autogenerated by
 * protocol/parse.py. Any changes should me made there, instead of here.
 */
#pragma once
#include <net/packet.h>
#include <boost/cstdint.hpp>
#include <net/PacketParameters.h>

namespace packet {
namespace protocol {

// request download agent patch file
class MC_REQUEST_DOWNLOAD_AGENT_PATCH_FILE : public Packet
{

public:
	enum { packetID = 33038 };

	MC_REQUEST_DOWNLOAD_AGENT_PATCH_FILE();

	const char* name() const;
	const char* doc() const;
	boost::uint16_t id() const;
	Buffer serialize() const;

	virtual ~MC_REQUEST_DOWNLOAD_AGENT_PATCH_FILE()
	{
	}

};

}
}