/*
 * NOTICE: Do not manually edit this file. It has been autogenerated by
 * protocol/parse.py. Any changes should me made there, instead of here.
 */
#pragma once
#include <net/packet.h>
#include <boost/cstdint.hpp>
#include <net/PacketParameters.h>

namespace packet {
namespace protocol {

// response set one config
class MC_RESPONSE_SET_ONE_CONFIG : public Packet
{
private:
	packet::int32 configid;
	packet::int32 confingstate;

public:
	enum { packetID = 31019 };

	MC_RESPONSE_SET_ONE_CONFIG(packet::int32 configid, packet::int32 confingstate);

	const char* name() const;
	const char* doc() const;
	boost::uint16_t id() const;
	Buffer serialize() const;
};

}
}