/*
 * NOTICE: Do not manually edit this file. It has been autogenerated by
 * protocol/parse.py. Any changes should me made there, instead of here.
 */
#pragma once
#include <net/packet.h>
#include <boost/cstdint.hpp>
#include <net/PacketParameters.h>

namespace packet {
namespace protocol {

// request keeper connect to match server
class MC_REQUEST_KEEPER_CONNECT_MATCHSERVER : public Packet
{

public:
	enum { packetID = 31011 };

	MC_REQUEST_KEEPER_CONNECT_MATCHSERVER();

	const char* name() const;
	const char* doc() const;
	boost::uint16_t id() const;
	Buffer serialize() const;
};

}
}