/*
 * NOTICE: Do not manually edit this file. It has been autogenerated by
 * protocol/parse.py. Any changes should me made there, instead of here.
 */
#pragma once
#include <net/packet.h>
#include <boost/cstdint.hpp>
#include <net/PacketParameters.h>

namespace packet {
namespace protocol {

// request Irrational User
class MC_REQUEST_XTRAP_DETECTCRACK : public Packet
{
private:
	packet::blob communicationbuffer;

public:
	enum { packetID = 8005 };

	MC_REQUEST_XTRAP_DETECTCRACK(packet::blob communicationbuffer);

	const char* name() const;
	const char* doc() const;
	boost::uint16_t id() const;
	Buffer serialize() const;
};

}
}