/*
 * NOTICE: Do not manually edit this file. It has been autogenerated by
 * protocol/parse.py. Any changes should me made there, instead of here.
 */
#pragma once
#include <net/packet.h>
#include <boost/cstdint.hpp>
#include <net/PacketParameters.h>

namespace packet {
namespace protocol {

// response current server state
class MC_RESPONSE_CONNECTION_STATE : public Packet
{
private:
	packet::int32 resut;

public:
	enum { packetID = 31008 };

	MC_RESPONSE_CONNECTION_STATE(packet::int32 resut);

	const char* name() const;
	const char* doc() const;
	boost::uint16_t id() const;
	Buffer serialize() const;
};

}
}