/*
 * NOTICE: Do not manually edit this file. It has been autogenerated by
 * protocol/parse.py. Any changes should me made there, instead of here.
 */
#pragma once
#include <net/packet.h>
#include <boost/cstdint.hpp>
#include <net/PacketParameters.h>

namespace packet {
namespace protocol {

// On Error
class Net_OnError : public Packet
{
private:
	packet::int32 ErrorCode;

public:
	enum { packetID = 313 };

	Net_OnError(packet::int32 ErrorCode);

	const char* name() const;
	const char* doc() const;
	boost::uint16_t id() const;
	Buffer serialize() const;

	virtual ~Net_OnError()
	{
	}

};

}
}