/*
 * NOTICE: Do not manually edit this file. It has been autogenerated by
 * protocol/parse.py. Any changes should me made there, instead of here.
 */
#pragma once
#include <net/packet.h>
#include <boost/cstdint.hpp>
#include <net/PacketParameters.h>

namespace packet {
namespace protocol {

// Skill
class Peer_ObjectSkill : public Packet
{
private:
	packet::floating_point Time;
	packet::int32 SkillID;
	packet::int32 SelType;

public:
	enum { packetID = 10036 };

	Peer_ObjectSkill(packet::floating_point Time, packet::int32 SkillID, packet::int32 SelType);

	const char* name() const;
	const char* doc() const;
	boost::uint16_t id() const;
	Buffer serialize() const;

	virtual ~Peer_ObjectSkill()
	{
	}

};

}
}