/*
 * NOTICE: Do not manually edit this file. It has been autogenerated by
 * protocol/parse.py. Any changes should me made there, instead of here.
 */
#pragma once
#include <net/packet.h>
#include <boost/cstdint.hpp>
#include <net/PacketParameters.h>

namespace packet {
namespace protocol {

// ShotMelee
class Peer_Shot_Melee : public Packet
{
private:
	packet::floating_point Time;
	packet::position Position;
	packet::int32 nShot;

public:
	enum { packetID = 10037 };

	Peer_Shot_Melee(packet::floating_point Time, packet::position Position, packet::int32 nShot);

	const char* name() const;
	const char* doc() const;
	boost::uint16_t id() const;
	Buffer serialize() const;

	virtual ~Peer_Shot_Melee()
	{
	}

};

}
}