/*
 * NOTICE: Do not manually edit this file. It has been autogenerated by
 * protocol/parse.py. Any changes should me made there, instead of here.
 */
#pragma once
#include <net/packet.h>
#include <boost/cstdint.hpp>
#include <net/PacketParameters.h>

namespace packet {
namespace protocol {

// HPAPInfo
class Peer_CharacterHPAPInfo : public Packet
{
private:
	packet::floating_point fHP;
	packet::floating_point fAP;

public:
	enum { packetID = 10014 };

	Peer_CharacterHPAPInfo(packet::floating_point fHP, packet::floating_point fAP);

	const char* name() const;
	const char* doc() const;
	boost::uint16_t id() const;
	Buffer serialize() const;

	virtual ~Peer_CharacterHPAPInfo()
	{
	}

};

}
}