/*
 * NOTICE: Do not manually edit this file. It has been autogenerated by
 * protocol/parse.py. Any changes should me made there, instead of here.
 */
#pragma once
#include <net/packet.h>
#include <boost/cstdint.hpp>
#include <net/PacketParameters.h>

namespace packet {
namespace protocol {

// React
class Peer_Reaction : public Packet
{
private:
	packet::floating_point Time;
	packet::int32 ReactionID;

public:
	enum { packetID = 10054 };

	Peer_Reaction(packet::floating_point Time, packet::int32 ReactionID);

	const char* name() const;
	const char* doc() const;
	boost::uint16_t id() const;
	Buffer serialize() const;

	virtual ~Peer_Reaction()
	{
	}

};

}
}