/*
 * NOTICE: Do not manually edit this file. It has been autogenerated by
 * protocol/parse.py. Any changes should me made there, instead of here.
 */
#pragma once
#include <net/packet.h>
#include <boost/cstdint.hpp>
#include <net/PacketParameters.h>

namespace packet {
namespace protocol {

// Dash
class Peer_Dash : public Packet
{
private:
	packet::blob DashInfo;

public:
	enum { packetID = 10045 };

	Peer_Dash(packet::blob DashInfo);

	const char* name() const;
	const char* doc() const;
	boost::uint16_t id() const;
	Buffer serialize() const;

	virtual ~Peer_Dash()
	{
	}

};

}
}