/*
 * NOTICE: Do not manually edit this file. It has been autogenerated by
 * protocol/parse.py. Any changes should me made there, instead of here.
 */
#pragma once
#include <net/packet.h>
#include <boost/cstdint.hpp>
#include <net/PacketParameters.h>

namespace packet {
namespace protocol {

// Object Damage
class Peer_ObjectDamage : public Packet
{
private:
	packet::MUID TargetUID;
	packet::int32 Damage;

public:
	enum { packetID = 10032 };

	Peer_ObjectDamage(packet::MUID TargetUID, packet::int32 Damage);

	const char* name() const;
	const char* doc() const;
	boost::uint16_t id() const;
	Buffer serialize() const;

	virtual ~Peer_ObjectDamage()
	{
	}

};

}
}