/*
 * NOTICE: Do not manually edit this file. It has been autogenerated by
 * protocol/parse.py. Any changes should me made there, instead of here.
 */
#pragma once
#include <net/packet.h>
#include <boost/cstdint.hpp>
#include <net/PacketParameters.h>

namespace packet {
namespace protocol {

// Change Object Weapon
class Peer_ObjectChangeWeapon : public Packet
{
private:
	packet::int32 WeaponID;

public:
	enum { packetID = 10022 };

	Peer_ObjectChangeWeapon(packet::int32 WeaponID);

	const char* name() const;
	const char* doc() const;
	boost::uint16_t id() const;
	Buffer serialize() const;

	virtual ~Peer_ObjectChangeWeapon()
	{
	}

};

}
}