/*
 * NOTICE: Do not manually edit this file. It has been autogenerated by
 * protocol/parse.py. Any changes should me made there, instead of here.
 */
#pragma once
#include <net/packet.h>
#include <boost/cstdint.hpp>
#include <net/PacketParameters.h>

namespace packet {
namespace protocol {

// Pong
class Peer_Pong_Time : public Packet
{
private:
	packet::uint32 IPAddress;
	packet::uint32 TimeStamp;

public:
	enum { packetID = 10008 };

	Peer_Pong_Time(packet::uint32 IPAddress, packet::uint32 TimeStamp);

	const char* name() const;
	const char* doc() const;
	boost::uint16_t id() const;
	Buffer serialize() const;

	virtual ~Peer_Pong_Time()
	{
	}

};

}
}