/*
 * NOTICE: Do not manually edit this file. It has been autogenerated by
 * protocol/parse.py. Any changes should me made there, instead of here.
 */
#pragma once
#include <net/packet.h>
#include <boost/cstdint.hpp>
#include <net/PacketParameters.h>

namespace packet {
namespace protocol {

// Quest Combat State
class Quest_Combat_State : public Packet
{
private:
	packet::vector CombatState;

public:
	enum { packetID = 6052 };

	Quest_Combat_State(packet::vector CombatState);

	const char* name() const;
	const char* doc() const;
	boost::uint16_t id() const;
	Buffer serialize() const;

	virtual ~Quest_Combat_State()
	{
	}

};

}
}