/*
 * NOTICE: Do not manually edit this file. It has been autogenerated by
 * protocol/parse.py. Any changes should me made there, instead of here.
 */
#pragma once
#include <net/packet.h>
#include <boost/cstdint.hpp>
#include <net/PacketParameters.h>

namespace packet {
namespace protocol {

// response monster bible info
class Quest_Bible_Response : public Packet
{
private:
	packet::MUID requester;
	packet::blob Monsterbibleinfo;

public:
	enum { packetID = 21015 };

	Quest_Bible_Response(packet::MUID requester, packet::blob Monsterbibleinfo);

	const char* name() const;
	const char* doc() const;
	boost::uint16_t id() const;
	Buffer serialize() const;
};

}
}