/*
 * NOTICE: Do not manually edit this file. It has been autogenerated by
 * protocol/parse.py. Any changes should me made there, instead of here.
 */
#pragma once
#include <net/packet.h>
#include <boost/cstdint.hpp>
#include <net/PacketParameters.h>

namespace packet {
namespace protocol {

// Checksum NPC Info
class Quest_Checksum_NPCInfo : public Packet
{
private:
	packet::MUID uidChar;
	packet::uint32 checksum;

public:
	enum { packetID = 6002 };

	Quest_Checksum_NPCInfo(packet::MUID uidChar, packet::uint32 checksum);

	const char* name() const;
	const char* doc() const;
	boost::uint16_t id() const;
	Buffer serialize() const;
};

}
}