/*
 * NOTICE: Do not manually edit this file. It has been autogenerated by
 * protocol/parse.py. Any changes should me made there, instead of here.
 */
#pragma once
#include <net/packet.h>
#include <boost/cstdint.hpp>
#include <net/PacketParameters.h>

namespace packet {
namespace protocol {

// Quest Game Info
class Quest_GameInfo : public Packet
{
private:
	packet::blob Info;

public:
	enum { packetID = 6051 };

	Quest_GameInfo(packet::blob Info);

	const char* name() const;
	const char* doc() const;
	boost::uint16_t id() const;
	Buffer serialize() const;

	virtual ~Quest_GameInfo()
	{
	}

};

}
}