/*
 * NOTICE: Do not manually edit this file. It has been autogenerated by
 * protocol/parse.py. Any changes should me made there, instead of here.
 */
#pragma once
#include <net/packet.h>
#include <boost/cstdint.hpp>
#include <net/PacketParameters.h>

namespace packet {
namespace protocol {

// NPC Dead
class Quest_Peer_NPC_Dead : public Packet
{
private:
	packet::MUID uidKillerPlayer;
	packet::MUID uidNPC;

public:
	enum { packetID = 6046 };

	Quest_Peer_NPC_Dead(packet::MUID uidKillerPlayer, packet::MUID uidNPC);

	const char* name() const;
	const char* doc() const;
	boost::uint16_t id() const;
	Buffer serialize() const;

	virtual ~Quest_Peer_NPC_Dead()
	{
	}

};

}
}