/*
 * NOTICE: Do not manually edit this file. It has been autogenerated by
 * protocol/parse.py. Any changes should me made there, instead of here.
 */
#pragma once
#include <net/packet.h>
#include <boost/cstdint.hpp>
#include <net/PacketParameters.h>

namespace packet {
namespace protocol {

// Request sell quest item
class Quest_item_sell : public Packet
{
private:
	packet::MUID uidChar;
	packet::int32 QuestItemID;
	packet::int32 Count;

public:
	enum { packetID = 21004 };

	Quest_item_sell(packet::MUID uidChar, packet::int32 QuestItemID, packet::int32 Count);

	const char* name() const;
	const char* doc() const;
	boost::uint16_t id() const;
	Buffer serialize() const;
};

}
}