/*
 * NOTICE: Do not manually edit this file. It has been autogenerated by
 * protocol/parse.py. Any changes should me made there, instead of here.
 */
#pragma once
#include <net/packet.h>
#include <boost/cstdint.hpp>
#include <net/PacketParameters.h>

namespace packet {
namespace protocol {

// Request Moveto Portal
class Quest_Request_Moveto_Portal : public Packet
{
private:
	packet::vector CurrSectorIndex;

public:
	enum { packetID = 6057 };

	Quest_Request_Moveto_Portal(packet::vector CurrSectorIndex);

	const char* name() const;
	const char* doc() const;
	boost::uint16_t id() const;
	Buffer serialize() const;
};

}
}