/*
 * NOTICE: Do not manually edit this file. It has been autogenerated by
 * protocol/parse.py. Any changes should me made there, instead of here.
 */
#pragma once
#include <net/packet.h>
#include <boost/cstdint.hpp>
#include <net/PacketParameters.h>

namespace packet {
namespace protocol {

// Quest Sector Start
class Quest_Sector_Start : public Packet
{
private:
	packet::vector SectorIndex;
	packet::uint8 RepeatIndex;

public:
	enum { packetID = 6053 };

	Quest_Sector_Start(packet::vector SectorIndex, packet::uint8 RepeatIndex);

	const char* name() const;
	const char* doc() const;
	boost::uint16_t id() const;
	Buffer serialize() const;
};

}
}