/*
 * NOTICE: Do not manually edit this file. It has been autogenerated by
 * protocol/parse.py. Any changes should me made there, instead of here.
 */
#pragma once
#include <net/packet.h>
#include <boost/cstdint.hpp>
#include <net/PacketParameters.h>

namespace packet {
namespace protocol {

// Quest Stage GameInfo
class Quest_Stage_GameInfo : public Packet
{
private:
	packet::vector Questlevel;
	packet::vector MapsetID;
	packet::uint32 QuestScenarioID;

public:
	enum { packetID = 6061 };

	Quest_Stage_GameInfo(packet::vector Questlevel, packet::vector MapsetID, packet::uint32 QuestScenarioID);

	const char* name() const;
	const char* doc() const;
	boost::uint16_t id() const;
	Buffer serialize() const;

	virtual ~Quest_Stage_GameInfo()
	{
	}

};

}
}