/*
 * NOTICE: Do not manually edit this file. It has been autogenerated by
 * protocol/parse.py. Any changes should me made there, instead of here.
 */
#pragma once
#include <net/packet.h>
#include <boost/cstdint.hpp>
#include <net/PacketParameters.h>

namespace packet {
namespace protocol {

// Change Stage Quest Mapset Setting
class Quest_State_Mapset : public Packet
{
private:
	packet::MUID uidStage;
	packet::vector QuestMapset;

public:
	enum { packetID = 6010 };

	Quest_State_Mapset(packet::MUID uidStage, packet::vector QuestMapset);

	const char* name() const;
	const char* doc() const;
	boost::uint16_t id() const;
	Buffer serialize() const;
};

}
}