/*
 * NOTICE: Do not manually edit this file. It has been autogenerated by
 * protocol/parse.py. Any changes should me made there, instead of here.
 */
#pragma once
#include <net/packet.h>
#include <boost/cstdint.hpp>
#include <net/PacketParameters.h>

namespace packet {
namespace protocol {

// response matchserver status
class responsematchserverststus : public Packet
{
private:
	packet::int32 isopenDB;
	packet::string serverreleaseversion;
	packet::uint8 connectedagentcount;

public:
	enum { packetID = 31005 };

	responsematchserverststus(packet::int32 isopenDB, packet::string serverreleaseversion, packet::uint8 connectedagentcount);

	const char* name() const;
	const char* doc() const;
	boost::uint16_t id() const;
	Buffer serialize() const;
};

}
}