/*
 * NOTICE: Do not manually edit this file. It has been autogenerated by
 * protocol/parse.py. Any changes should me made there, instead of here.
 */
#pragma once
#include <net/packet.h>
#include <boost/cstdint.hpp>
#include <net/PacketParameters.h>

namespace packet {
namespace protocol {

// Response Game Info
class ResponseGameInfo : public Packet
{
private:
	packet::MUID uidStage;
	packet::blob GameInfo;
	packet::blob RuleInfo;
	packet::blob PlayerInfo;

public:
	enum { packetID = 1452 };

	ResponseGameInfo(packet::MUID uidStage, packet::blob GameInfo, packet::blob RuleInfo, packet::blob PlayerInfo);

	const char* name() const;
	const char* doc() const;
	boost::uint16_t id() const;
	Buffer serialize() const;
};

}
}