/*
 * NOTICE: Do not manually edit this file. It has been autogenerated by
 * protocol/parse.py. Any changes should me made there, instead of here.
 */
#pragma once
#include <net/packet.h>
#include <boost/cstdint.hpp>
#include <net/PacketParameters.h>

namespace packet {
namespace protocol {

// Follow User to Stage
class Stage_Follow : public Packet
{
private:
	packet::string strTarget;

public:
	enum { packetID = 1309 };

	Stage_Follow(packet::string strTarget);

	const char* name() const;
	const char* doc() const;
	boost::uint16_t id() const;
	Buffer serialize() const;

	virtual ~Stage_Follow()
	{
	}

};

}
}