/*
 * NOTICE: Do not manually edit this file. It has been autogenerated by
 * protocol/parse.py. Any changes should me made there, instead of here.
 */
#pragma once
#include <net/packet.h>
#include <boost/cstdint.hpp>
#include <net/PacketParameters.h>

namespace packet {
namespace protocol {

// Enter Stage Battle
class Stage_EnterBattle : public Packet
{
private:
	packet::uint8 Param;
	packet::blob CharData;

public:
	enum { packetID = 1402 };

	Stage_EnterBattle(packet::uint8 Param, packet::blob CharData);

	const char* name() const;
	const char* doc() const;
	boost::uint16_t id() const;
	Buffer serialize() const;

	virtual ~Stage_EnterBattle()
	{
	}

};

}
}