/*
 * NOTICE: Do not manually edit this file. It has been autogenerated by
 * protocol/parse.py. Any changes should me made there, instead of here.
 */
#pragma once
#include <net/packet.h>
#include <boost/cstdint.hpp>
#include <net/PacketParameters.h>

namespace packet {
namespace protocol {

// Join a Stage
class Stage_Join : public Packet
{
private:
	packet::MUID uidPlayer;
	packet::MUID uidStage;
	packet::uint32 nRoomNo;
	packet::string StageName;

public:
	enum { packetID = 1303 };

	Stage_Join(packet::MUID uidPlayer, packet::MUID uidStage, packet::uint32 nRoomNo, packet::string StageName);

	const char* name() const;
	const char* doc() const;
	boost::uint16_t id() const;
	Buffer serialize() const;

	virtual ~Stage_Join()
	{
	}

};

}
}