/*
 * NOTICE: Do not manually edit this file. It has been autogenerated by
 * protocol/parse.py. Any changes should me made there, instead of here.
 */
#pragma once
#include <net/packet.h>
#include <boost/cstdint.hpp>
#include <net/PacketParameters.h>

namespace packet {
namespace protocol {

// Setting up Stage
class Stage_StageSetting : public Packet
{
private:
	packet::MUID uidPlayer;
	packet::MUID uidStage;
	packet::blob StageSetting;

public:
	enum { packetID = 1413 };

	Stage_StageSetting(packet::MUID uidPlayer, packet::MUID uidStage, packet::blob StageSetting);

	const char* name() const;
	const char* doc() const;
	boost::uint16_t id() const;
	Buffer serialize() const;
};

}
}