/*
 * NOTICE: Do not manually edit this file. It has been autogenerated by
 * protocol/parse.py. Any changes should me made there, instead of here.
 */
#pragma once
#include <boost/cstdint.hpp>
#include <cockpit/packet/Packet.h>
#include <cockpit/packet/Parameters.h>

namespace cockpit {
namespace packet {
namespace protocol {

// Announce
class Admin_Announce : public Packet
{
private:
	packet::MUID uidAdmin;
	packet::string Msg;
	packet::uint32 MsgType;

public:
	enum { packetID = 501 };

	Admin_Announce(const packet::MUID& uidAdmin, const packet::string& Msg, const packet::uint32& MsgType);

	const char* name() const;
	const char* doc() const;
	boost::uint16_t id() const;
	Buffer serialize() const;

	~Admin_Announce()
	{
	}

};

}
}
}
