/*
 * NOTICE: Do not manually edit this file. It has been autogenerated by
 * protocol/parse.py. Any changes should me made there, instead of here.
 */
#pragma once
#include <boost/cstdint.hpp>
#include <cockpit/packet/Packet.h>
#include <cockpit/packet/Parameters.h>

namespace cockpit {
namespace packet {
namespace protocol {

// Request Ban Player
class Admin_RequestBanPlayer : public Packet
{
private:
	packet::MUID uidAdmin;
	packet::string uidTargetCharName;

public:
	enum { packetID = 515 };

	Admin_RequestBanPlayer(packet::MUID uidAdmin, packet::string uidTargetCharName);

	const char* name() const;
	const char* doc() const;
	boost::uint16_t id() const;
	Buffer serialize() const;

	~Admin_RequestBanPlayer()
	{
	}

};

}
}
}