/*
 * NOTICE: Do not manually edit this file. It has been autogenerated by
 * protocol/parse.py. Any changes should me made there, instead of here.
 */
#pragma once
#include <boost/cstdint.hpp>
#include <cockpit/packet/Packet.h>
#include <cockpit/packet/Parameters.h>

namespace cockpit {
namespace packet {
namespace protocol {

// Connect Agent to MatchServer
class Agent_Connect : public Packet
{
private:
	packet::string Address;
	packet::int32 Port;

public:
	enum { packetID = 5021 };

	Agent_Connect(const packet::string& Address, const packet::int32& Port);

	const char* name() const;
	const char* doc() const;
	boost::uint16_t id() const;
	Buffer serialize() const;

	~Agent_Connect()
	{
	}

};

}
}
}
