/*
 * NOTICE: Do not manually edit this file. It has been autogenerated by
 * protocol/parse.py. Any changes should me made there, instead of here.
 */
#pragma once
#include <boost/cstdint.hpp>
#include <cockpit/packet/Packet.h>
#include <cockpit/packet/Parameters.h>

namespace cockpit {
namespace packet {
namespace protocol {

// Join a Channel From Name
class Channel_RequestJoinFromName : public Packet
{
private:
	packet::MUID uidPlayer;
	packet::int32 nChannelType;
	packet::int32 zero;
	packet::string ChannelName;

public:
	enum { packetID = 1206 };

	Channel_RequestJoinFromName(packet::MUID uidPlayer, packet::int32 nChannelType, packet::int32 zero, packet::string ChannelName);

	const char* name() const;
	const char* doc() const;
	boost::uint16_t id() const;
	Buffer serialize() const;

	~Channel_RequestJoinFromName()
	{
	}

};

}
}
}
