/*
 * NOTICE: Do not manually edit this file. It has been autogenerated by
 * protocol/parse.py. Any changes should me made there, instead of here.
 */
#pragma once
#include <boost/cstdint.hpp>
#include <cockpit/packet/Packet.h>
#include <cockpit/packet/Parameters.h>

namespace cockpit {
namespace packet {
namespace protocol {

// Request Chat to Channel
class Channel_Request_Chat : public Packet
{
private:
	packet::MUID uidPlayer;
	packet::MUID uidChannel;
	packet::string Chat;

public:
	enum { packetID = 1225 };

	Channel_Request_Chat(packet::MUID uidPlayer, packet::MUID uidChannel, packet::string Chat);

	const char* name() const;
	const char* doc() const;
	boost::uint16_t id() const;
	Buffer serialize() const;

	~Channel_Request_Chat()
	{
	}

};

}
}
}
