/*
 * NOTICE: Do not manually edit this file. It has been autogenerated by
 * protocol/parse.py. Any changes should me made there, instead of here.
 */
#pragma once
#include <boost/cstdint.hpp>
#include <cockpit/packet/Packet.h>
#include <cockpit/packet/Parameters.h>

namespace cockpit {
namespace packet {
namespace protocol {

// Chat to Channel
class Channel_Chat : public Packet
{
private:
	packet::MUID uidChannel;
	packet::string PlayerName;
	packet::string Chat;
	packet::int32 nGrade;

public:
	enum { packetID = 1226 };

	Channel_Chat(packet::MUID uidChannel, packet::string PlayerName, packet::string Chat, packet::int32 nGrade);

	const char* name() const;
	const char* doc() const;
	boost::uint16_t id() const;
	Buffer serialize() const;

	~Channel_Chat()
	{
	}

};

}
}
}
