/*
 * NOTICE: Do not manually edit this file. It has been autogenerated by
 * protocol/parse.py. Any changes should me made there, instead of here.
 */
#pragma once
#include <boost/cstdint.hpp>
#include <cockpit/packet/Packet.h>
#include <cockpit/packet/Parameters.h>

namespace cockpit {
namespace packet {
namespace protocol {

// Response Channel Player List
class Channel_ResponsePlayerList : public Packet
{
private:
	packet::uint8 TotalPlayerCount;
	packet::uint8 PlayerListPage;
	packet::blob PlayerList;

public:
	enum { packetID = 1222 };

	Channel_ResponsePlayerList(packet::uint8 TotalPlayerCount, packet::uint8 PlayerListPage, packet::blob PlayerList);

	const char* name() const;
	const char* doc() const;
	boost::uint16_t id() const;
	Buffer serialize() const;

	~Channel_ResponsePlayerList()
	{
	}

};

}
}
}
