/*
 * NOTICE: Do not manually edit this file. It has been autogenerated by
 * protocol/parse.py. Any changes should me made there, instead of here.
 */
#pragma once
#include <boost/cstdint.hpp>
#include <cockpit/packet/Packet.h>
#include <cockpit/packet/Parameters.h>

namespace cockpit {
namespace packet {
namespace protocol {

// Response Join a Channel
class Channel_ResponseJoin : public Packet
{
private:
	packet::MUID uidChannel;
	packet::int32 ChannelType;
	packet::string ChannelName;
	packet::boolean EnableInterface;

public:
	enum { packetID = 1207 };

	Channel_ResponseJoin(const packet::MUID& uidChannel, const packet::int32& ChannelType, const packet::string& ChannelName, const packet::boolean& EnableInterface);

	const char* name() const;
	const char* doc() const;
	boost::uint16_t id() const;
	Buffer serialize() const;

	~Channel_ResponseJoin()
	{
	}

};

}
}
}
