/*
 * NOTICE: Do not manually edit this file. It has been autogenerated by
 * protocol/parse.py. Any changes should me made there, instead of here.
 */
#pragma once
#include <boost/cstdint.hpp>
#include <cockpit/packet/Packet.h>
#include <cockpit/packet/Parameters.h>

namespace cockpit {
namespace packet {
namespace protocol {

// Response Channel All Player List
class Channel_ResponseAllPlayerList : public Packet
{
private:
	packet::MUID uidChannel;
	packet::blob PlayerList;

public:
	enum { packetID = 1233 };

	Channel_ResponseAllPlayerList(packet::MUID uidChannel, packet::blob PlayerList);

	const char* name() const;
	const char* doc() const;
	boost::uint16_t id() const;
	Buffer serialize() const;

	~Channel_ResponseAllPlayerList()
	{
	}

};

}
}
}
