/*
 * NOTICE: Do not manually edit this file. It has been autogenerated by
 * protocol/parse.py. Any changes should me made there, instead of here.
 */
#pragma once
#include <boost/cstdint.hpp>
#include <cockpit/packet/Packet.h>
#include <cockpit/packet/Parameters.h>

namespace cockpit {
namespace packet {
namespace protocol {

// Invite a user to ChatRoom
class ChatRoom_Invite : public Packet
{
private:
	packet::string SenderName;
	packet::string TargetName;
	packet::string ChatRoomName;

public:
	enum { packetID = 1661 };

	ChatRoom_Invite(packet::string SenderName, packet::string TargetName, packet::string ChatRoomName);

	const char* name() const;
	const char* doc() const;
	boost::uint16_t id() const;
	Buffer serialize() const;

	~ChatRoom_Invite()
	{
	}

};

}
}
}