/*
 * NOTICE: Do not manually edit this file. It has been autogenerated by
 * protocol/parse.py. Any changes should me made there, instead of here.
 */
#pragma once
#include <boost/cstdint.hpp>
#include <cockpit/packet/Packet.h>
#include <cockpit/packet/Parameters.h>

namespace cockpit {
namespace packet {
namespace protocol {

// Request Spawn
class Game_Requst_Spawn : public Packet
{
private:
	packet::MUID CharUID;
	packet::position Position;
	packet::direction Direction;

public:
	enum { packetID = 1515 };

	Game_Requst_Spawn(packet::MUID CharUID, packet::position Position, packet::direction Direction);

	const char* name() const;
	const char* doc() const;
	boost::uint16_t id() const;
	Buffer serialize() const;

	~Game_Requst_Spawn()
	{
	}

};

}
}
}
