/*
 * NOTICE: Do not manually edit this file. It has been autogenerated by
 * protocol/parse.py. Any changes should me made there, instead of here.
 */
#pragma once
#include <boost/cstdint.hpp>
#include <cockpit/packet/Packet.h>
#include <cockpit/packet/Parameters.h>

namespace cockpit {
namespace packet {
namespace protocol {

// Set User Option
class Match_UserOption : public Packet
{
private:
	packet::uint32 OptionFlags;

public:
	enum { packetID = 1605 };

	Match_UserOption(const packet::uint32& OptionFlags);

	const char* name() const;
	const char* doc() const;
	boost::uint16_t id() const;
	Buffer serialize() const;

	~Match_UserOption()
	{
	}

};

}
}
}
