/*
 * NOTICE: Do not manually edit this file. It has been autogenerated by
 * protocol/parse.py. Any changes should me made there, instead of here.
 */
#pragma once
#include <boost/cstdint.hpp>
#include <cockpit/packet/Packet.h>
#include <cockpit/packet/Parameters.h>

namespace cockpit {
namespace packet {
namespace protocol {

// Assign Commander
class Match_Assign_Commander : public Packet
{
private:
	packet::MUID uidRedCommander;
	packet::MUID uidBlueCommander;

public:
	enum { packetID = 1551 };

	Match_Assign_Commander(const packet::MUID& uidRedCommander, const packet::MUID& uidBlueCommander);

	const char* name() const;
	const char* doc() const;
	boost::uint16_t id() const;
	Buffer serialize() const;

	~Match_Assign_Commander()
	{
	}

};

}
}
}
