/*
 * NOTICE: Do not manually edit this file. It has been autogenerated by
 * protocol/parse.py. Any changes should me made there, instead of here.
 */
#pragma once
#include <boost/cstdint.hpp>
#include <cockpit/packet/Packet.h>
#include <cockpit/packet/Parameters.h>

namespace cockpit {
namespace packet {
namespace protocol {

// Add a Friend
class Match_Friend_Add : public Packet
{
private:
	packet::string Name;

public:
	enum { packetID = 1901 };

	Match_Friend_Add(packet::string Name);

	const char* name() const;
	const char* doc() const;
	boost::uint16_t id() const;
	Buffer serialize() const;

	~Match_Friend_Add()
	{
	}

};

}
}
}
