/*
 * NOTICE: Do not manually edit this file. It has been autogenerated by
 * protocol/parse.py. Any changes should me made there, instead of here.
 */
#pragma once
#include <boost/cstdint.hpp>
#include <cockpit/packet/Packet.h>
#include <cockpit/packet/Parameters.h>

namespace cockpit {
namespace packet {
namespace protocol {

// Request Create Character
class Match_RequestCreateChar : public Packet
{
private:
	packet::MUID uid;
	packet::uint32 CharIndex;
	packet::string Name;
	packet::uint32 Sex;
	packet::uint32 Hair;
	packet::uint32 Face;
	packet::uint32 Costume;

public:
	enum { packetID = 1711 };

	Match_RequestCreateChar(packet::MUID uid, packet::uint32 CharIndex, packet::string Name, packet::uint32 Sex, packet::uint32 Hair, packet::uint32 Face, packet::uint32 Costume);

	const char* name() const;
	const char* doc() const;
	boost::uint16_t id() const;
	Buffer serialize() const;

	~Match_RequestCreateChar()
	{
	}

};

}
}
}
