/*
 * NOTICE: Do not manually edit this file. It has been autogenerated by
 * protocol/parse.py. Any changes should me made there, instead of here.
 */
#pragma once
#include <boost/cstdint.hpp>
#include <cockpit/packet/Packet.h>
#include <cockpit/packet/Parameters.h>

namespace cockpit {
namespace packet {
namespace protocol {

// Request EmblemURL
class Match_Clan_Request_EmblemURL : public Packet
{
private:
	packet::blob ClanURLList;

public:
	enum { packetID = 2051 };

	Match_Clan_Request_EmblemURL(const packet::blob& ClanURLList);

	const char* name() const;
	const char* doc() const;
	boost::uint16_t id() const;
	Buffer serialize() const;

	~Match_Clan_Request_EmblemURL()
	{
	}

};

}
}
}
