/*
 * NOTICE: Do not manually edit this file. It has been autogenerated by
 * protocol/parse.py. Any changes should me made there, instead of here.
 */
#pragma once
#include <boost/cstdint.hpp>
#include <cockpit/packet/Packet.h>
#include <cockpit/packet/Parameters.h>

namespace cockpit {
namespace packet {
namespace protocol {

// Ask Join Agreement
class Match_Clan_AskJoinAgreement : public Packet
{
private:
	packet::string ClanName;
	packet::MUID uidClanAdmin;
	packet::string szClanAdmin;

public:
	enum { packetID = 2010 };

	Match_Clan_AskJoinAgreement(packet::string ClanName, packet::MUID uidClanAdmin, packet::string szClanAdmin);

	const char* name() const;
	const char* doc() const;
	boost::uint16_t id() const;
	Buffer serialize() const;

	~Match_Clan_AskJoinAgreement()
	{
	}

};

}
}
}
