/*
 * NOTICE: Do not manually edit this file. It has been autogenerated by
 * protocol/parse.py. Any changes should me made there, instead of here.
 */
#pragma once
#include <boost/cstdint.hpp>
#include <cockpit/packet/Packet.h>
#include <cockpit/packet/Parameters.h>

namespace cockpit {
namespace packet {
namespace protocol {

// Response Peer Relay
class Match_ResponsePeerRelay : public Packet
{
private:
	packet::MUID PeerCharUID;

public:
	enum { packetID = 1472 };

	Match_ResponsePeerRelay(packet::MUID PeerCharUID);

	const char* name() const;
	const char* doc() const;
	boost::uint16_t id() const;
	Buffer serialize() const;

	~Match_ResponsePeerRelay()
	{
	}

};

}
}
}