/*
 * NOTICE: Do not manually edit this file. It has been autogenerated by
 * protocol/parse.py. Any changes should me made there, instead of here.
 */
#pragma once
#include <boost/cstdint.hpp>
#include <cockpit/packet/Packet.h>
#include <cockpit/packet/Parameters.h>

namespace cockpit {
namespace packet {
namespace protocol {

// Message to Friends
class Match_Friend_Msg : public Packet
{
private:
	packet::string Msg;

public:
	enum { packetID = 1905 };

	Match_Friend_Msg(packet::string Msg);

	const char* name() const;
	const char* doc() const;
	boost::uint16_t id() const;
	Buffer serialize() const;

	~Match_Friend_Msg()
	{
	}

};

}
}
}
