/*
 * NOTICE: Do not manually edit this file. It has been autogenerated by
 * protocol/parse.py. Any changes should me made there, instead of here.
 */
#pragma once
#include <boost/cstdint.hpp>
#include <cockpit/packet/Packet.h>
#include <cockpit/packet/Parameters.h>

namespace cockpit {
namespace packet {
namespace protocol {

// Request Account Character Info
class Match_RequestAccountCharInfo : public Packet
{
private:
	packet::int8 CharNum;

public:
	enum { packetID = 1719 };

	Match_RequestAccountCharInfo(const packet::int8& CharNum);

	const char* name() const;
	const char* doc() const;
	boost::uint16_t id() const;
	Buffer serialize() const;

	~Match_RequestAccountCharInfo()
	{
	}

};

}
}
}
