/*
 * NOTICE: Do not manually edit this file. It has been autogenerated by
 * protocol/parse.py. Any changes should me made there, instead of here.
 */
#pragma once
#include <boost/cstdint.hpp>
#include <cockpit/packet/Packet.h>
#include <cockpit/packet/Parameters.h>

namespace cockpit {
namespace packet {
namespace protocol {

// Clan Msg
class Match_Clan_Msg : public Packet
{
private:
	packet::string SenderName;
	packet::string Msg;

public:
	enum { packetID = 2022 };

	Match_Clan_Msg(packet::string SenderName, packet::string Msg);

	const char* name() const;
	const char* doc() const;
	boost::uint16_t id() const;
	Buffer serialize() const;

	~Match_Clan_Msg()
	{
	}

};

}
}
}