/*
 * NOTICE: Do not manually edit this file. It has been autogenerated by
 * protocol/parse.py. Any changes should me made there, instead of here.
 */
#pragma once
#include <boost/cstdint.hpp>
#include <cockpit/packet/Packet.h>
#include <cockpit/packet/Parameters.h>

namespace cockpit {
namespace packet {
namespace protocol {

// Answer Sponsor's Agreement
class Match_Clan_AnswerSponsorAgreement : public Packet
{
private:
	packet::int32 RequestID;
	packet::MUID uidClanMaster;
	packet::string SponsorCharName;
	packet::boolean Answer;

public:
	enum { packetID = 2003 };

	Match_Clan_AnswerSponsorAgreement(const packet::int32& RequestID, const packet::MUID& uidClanMaster, const packet::string& SponsorCharName, const packet::boolean& Answer);

	const char* name() const;
	const char* doc() const;
	boost::uint16_t id() const;
	Buffer serialize() const;

	~Match_Clan_AnswerSponsorAgreement()
	{
	}

};

}
}
}
