/*
 * NOTICE: Do not manually edit this file. It has been autogenerated by
 * protocol/parse.py. Any changes should me made there, instead of here.
 */
#pragma once
#include <boost/cstdint.hpp>
#include <cockpit/packet/Packet.h>
#include <cockpit/packet/Parameters.h>

namespace cockpit {
namespace packet {
namespace protocol {

// Request Select Character
class Match_RequestSelectChar : public Packet
{
private:
	packet::MUID uid;
	packet::uint32 CharIndex;

public:
	enum { packetID = 1703 };

	Match_RequestSelectChar(const packet::MUID& uid, const packet::uint32& CharIndex);

	const char* name() const;
	const char* doc() const;
	boost::uint16_t id() const;
	Buffer serialize() const;

	~Match_RequestSelectChar()
	{
	}

};

}
}
}
