/*
 * NOTICE: Do not manually edit this file. It has been autogenerated by
 * protocol/parse.py. Any changes should me made there, instead of here.
 */
#pragma once
#include <boost/cstdint.hpp>
#include <cockpit/packet/Packet.h>
#include <cockpit/packet/Parameters.h>

namespace cockpit {
namespace packet {
namespace protocol {

// Response Change ClanGrade
class Match_Clan_Master_ResponseChangeGrade : public Packet
{
private:
	packet::int32 Result;

public:
	enum { packetID = 2018 };

	Match_Clan_Master_ResponseChangeGrade(const packet::int32& Result);

	const char* name() const;
	const char* doc() const;
	boost::uint16_t id() const;
	Buffer serialize() const;

	~Match_Clan_Master_ResponseChangeGrade()
	{
	}

};

}
}
}
