/*
 * NOTICE: Do not manually edit this file. It has been autogenerated by
 * protocol/parse.py. Any changes should me made there, instead of here.
 */
#pragma once
#include <boost/cstdint.hpp>
#include <cockpit/packet/Packet.h>
#include <cockpit/packet/Parameters.h>

namespace cockpit {
namespace packet {
namespace protocol {

// choose admin as commander
class MC_ADMIN_ASSASIN : public Packet
{

public:
	enum { packetID = 536 };

	MC_ADMIN_ASSASIN();

	const char* name() const;
	const char* doc() const;
	boost::uint16_t id() const;
	Buffer serialize() const;

	~MC_ADMIN_ASSASIN()
	{
	}

};

}
}
}