/*
 * NOTICE: Do not manually edit this file. It has been autogenerated by
 * protocol/parse.py. Any changes should me made there, instead of here.
 */
#pragma once
#include <boost/cstdint.hpp>
#include <cockpit/packet/Packet.h>
#include <cockpit/packet/Parameters.h>

namespace cockpit {
namespace packet {
namespace protocol {

// route updated user equip info
class MC_MATCH_ROUTE_UPDATE_STAGE_EQUIP_LOOK : public Packet
{
private:
	packet::MUID useruid;
	packet::int32 parts;
	packet::int32 itemid;

public:
	enum { packetID = 1828 };

	MC_MATCH_ROUTE_UPDATE_STAGE_EQUIP_LOOK(const packet::MUID& useruid, const packet::int32& parts, const packet::int32& itemid);

	const char* name() const;
	const char* doc() const;
	boost::uint16_t id() const;
	Buffer serialize() const;

	~MC_MATCH_ROUTE_UPDATE_STAGE_EQUIP_LOOK()
	{
	}

};

}
}
}
