/*
 * NOTICE: Do not manually edit this file. It has been autogenerated by
 * protocol/parse.py. Any changes should me made there, instead of here.
 */
#pragma once
#include <boost/cstdint.hpp>
#include <cockpit/packet/Packet.h>
#include <cockpit/packet/Parameters.h>

namespace cockpit {
namespace packet {
namespace protocol {

// MC_REQUEST_RESOURCE_CRC32
class MC_REQUEST_RESOURCE_CRC32 : public Packet
{
private:
	packet::uint32 key;

public:
	enum { packetID = 11001 };

	MC_REQUEST_RESOURCE_CRC32(const packet::uint32& key);

	const char* name() const;
	const char* doc() const;
	boost::uint16_t id() const;
	Buffer serialize() const;

	~MC_REQUEST_RESOURCE_CRC32()
	{
	}

};

}
}
}
