/*
 * NOTICE: Do not manually edit this file. It has been autogenerated by
 * protocol/parse.py. Any changes should me made there, instead of here.
 */
#pragma once
#include <boost/cstdint.hpp>
#include <cockpit/packet/Packet.h>
#include <cockpit/packet/Parameters.h>

namespace cockpit {
namespace packet {
namespace protocol {

// Pong
class Net_Pong : public Packet
{
private:
	packet::uint32 TimeStamp;

public:
	enum { packetID = 323 };

	Net_Pong(packet::uint32 TimeStamp);

	const char* name() const;
	const char* doc() const;
	boost::uint16_t id() const;
	Buffer serialize() const;

	~Net_Pong()
	{
	}

};

}
}
}
