/*
 * NOTICE: Do not manually edit this file. It has been autogenerated by
 * protocol/parse.py. Any changes should me made there, instead of here.
 */
#pragma once
#include <boost/cstdint.hpp>
#include <cockpit/packet/Packet.h>
#include <cockpit/packet/Parameters.h>

namespace cockpit {
namespace packet {
namespace protocol {

// Ping
class Net_Ping : public Packet
{
private:
	packet::uint32 TimeStamp;

public:
	enum { packetID = 322 };

	Net_Ping(packet::uint32 TimeStamp);

	const char* name() const;
	const char* doc() const;
	boost::uint16_t id() const;
	Buffer serialize() const;

	~Net_Ping()
	{
	}

};

}
}
}
