/*
 * NOTICE: Do not manually edit this file. It has been autogenerated by
 * protocol/parse.py. Any changes should me made there, instead of here.
 */
#pragma once
#include <boost/cstdint.hpp>
#include <cockpit/packet/Packet.h>
#include <cockpit/packet/Parameters.h>

namespace cockpit {
namespace packet {
namespace protocol {

// NPC Skill Start
class Quest_Peer_NPC_Skill_Execute : public Packet
{
private:
	packet::MUID uidOwner;
	packet::int32 nSkill;
	packet::MUID uidTarget;
	packet::position targetPos;

public:
	enum { packetID = 6045 };

	Quest_Peer_NPC_Skill_Execute(packet::MUID uidOwner, packet::int32 nSkill, packet::MUID uidTarget, packet::position targetPos);

	const char* name() const;
	const char* doc() const;
	boost::uint16_t id() const;
	Buffer serialize() const;

	~Quest_Peer_NPC_Skill_Execute()
	{
	}

};

}
}
}