/*
 * NOTICE: Do not manually edit this file. It has been autogenerated by
 * protocol/parse.py. Any changes should me made there, instead of here.
 */
#pragma once
#include <boost/cstdint.hpp>
#include <cockpit/packet/Packet.h>
#include <cockpit/packet/Parameters.h>

namespace cockpit {
namespace packet {
namespace protocol {

// Response my quest item list
class Quest_item_response : public Packet
{
private:
	packet::blob Myquestitemlist;

public:
	enum { packetID = 21001 };

	Quest_item_response(packet::blob Myquestitemlist);

	const char* name() const;
	const char* doc() const;
	boost::uint16_t id() const;
	Buffer serialize() const;

	~Quest_item_response()
	{
	}

};

}
}
}