/*
 * NOTICE: Do not manually edit this file. It has been autogenerated by
 * protocol/parse.py. Any changes should me made there, instead of here.
 */
#pragma once
#include <boost/cstdint.hpp>
#include <cockpit/packet/Packet.h>
#include <cockpit/packet/Parameters.h>

namespace cockpit {
namespace packet {
namespace protocol {

// Moveto Portal
class Quest_Moveto_Portal : public Packet
{
private:
	packet::int8 SectorIndex;
	packet::uint8 RepeatIndex;
	packet::MUID uidPlayer;

public:
	enum { packetID = 6058 };

	Quest_Moveto_Portal(const packet::int8& SectorIndex, const packet::uint8& RepeatIndex, const packet::MUID& uidPlayer);

	const char* name() const;
	const char* doc() const;
	boost::uint16_t id() const;
	Buffer serialize() const;

	~Quest_Moveto_Portal()
	{
	}

};

}
}
}
