/*
 * NOTICE: Do not manually edit this file. It has been autogenerated by
 * protocol/parse.py. Any changes should me made there, instead of here.
 */
#pragma once
#include <boost/cstdint.hpp>
#include <cockpit/packet/Packet.h>
#include <cockpit/packet/Parameters.h>

namespace cockpit {
namespace packet {
namespace protocol {

// Request stage quest level
class Quest_RequestLevel : public Packet
{
private:
	packet::MUID sender;

public:
	enum { packetID = 6101 };

	Quest_RequestLevel(packet::MUID sender);

	const char* name() const;
	const char* doc() const;
	boost::uint16_t id() const;
	Buffer serialize() const;

	~Quest_RequestLevel()
	{
	}

};

}
}
}
