/*
 * NOTICE: Do not manually edit this file. It has been autogenerated by
 * protocol/parse.py. Any changes should me made there, instead of here.
 */
#pragma once
#include <boost/cstdint.hpp>
#include <cockpit/packet/Packet.h>
#include <cockpit/packet/Parameters.h>

namespace cockpit {
namespace packet {
namespace protocol {

// Request Moveto Portal
class Quest_Request_Moveto_Portal : public Packet
{
private:
	packet::int8 CurrSectorIndex;

public:
	enum { packetID = 6057 };

	Quest_Request_Moveto_Portal(const packet::int8& CurrSectorIndex);

	const char* name() const;
	const char* doc() const;
	boost::uint16_t id() const;
	Buffer serialize() const;

	~Quest_Request_Moveto_Portal()
	{
	}

};

}
}
}
