/*
 * NOTICE: Do not manually edit this file. It has been autogenerated by
 * protocol/parse.py. Any changes should me made there, instead of here.
 */
#pragma once
#include <boost/cstdint.hpp>
#include <cockpit/packet/Packet.h>
#include <cockpit/packet/Parameters.h>

namespace cockpit {
namespace packet {
namespace protocol {

// Send survival top ranking list
class Quest_Survival_Ranking : public Packet
{
private:
	packet::blob Rankinglist;

public:
	enum { packetID = 6104 };

	Quest_Survival_Ranking(packet::blob Rankinglist);

	const char* name() const;
	const char* doc() const;
	boost::uint16_t id() const;
	Buffer serialize() const;

	~Quest_Survival_Ranking()
	{
	}

};

}
}
}
