/*
 * NOTICE: Do not manually edit this file. It has been autogenerated by
 * protocol/parse.py. Any changes should me made there, instead of here.
 */
#pragma once
#include <boost/cstdint.hpp>
#include <cockpit/packet/Packet.h>
#include <cockpit/packet/Parameters.h>

namespace cockpit {
namespace packet {
namespace protocol {

// Quest Player Dead
class Quest_PlayerDead : public Packet
{
private:
	packet::MUID Victim;

public:
	enum { packetID = 6008 };

	Quest_PlayerDead(packet::MUID Victim);

	const char* name() const;
	const char* doc() const;
	boost::uint16_t id() const;
	Buffer serialize() const;

	~Quest_PlayerDead()
	{
	}

};

}
}
}