/*
 * NOTICE: Do not manually edit this file. It has been autogenerated by
 * protocol/parse.py. Any changes should me made there, instead of here.
 */
#pragma once
#include <boost/cstdint.hpp>
#include <cockpit/packet/Packet.h>
#include <cockpit/packet/Parameters.h>

namespace cockpit {
namespace packet {
namespace protocol {

// Entrust Npc Control
class Quest_Entrust_NPC_Control : public Packet
{
private:
	packet::MUID uidChar;
	packet::MUID nNpcUID;

public:
	enum { packetID = 6001 };

	Quest_Entrust_NPC_Control(const packet::MUID& uidChar, const packet::MUID& nNpcUID);

	const char* name() const;
	const char* doc() const;
	boost::uint16_t id() const;
	Buffer serialize() const;

	~Quest_Entrust_NPC_Control()
	{
	}

};

}
}
}
