/*
 * NOTICE: Do not manually edit this file. It has been autogenerated by
 * protocol/parse.py. Any changes should me made there, instead of here.
 */
#pragma once
#include <boost/cstdint.hpp>
#include <cockpit/packet/Packet.h>
#include <cockpit/packet/Parameters.h>

namespace cockpit {
namespace packet {
namespace protocol {

// Response slot info
class Quest_Resonse_SlotInfo : public Packet
{
private:
	packet::MUID Owner1;
	packet::int32 ItemID1;
	packet::MUID Owner2;
	packet::int32 ItemID2;

public:
	enum { packetID = 21012 };

	Quest_Resonse_SlotInfo(packet::MUID Owner1, packet::int32 ItemID1, packet::MUID Owner2, packet::int32 ItemID2);

	const char* name() const;
	const char* doc() const;
	boost::uint16_t id() const;
	Buffer serialize() const;

	~Quest_Resonse_SlotInfo()
	{
	}

};

}
}
}
