/*
 * NOTICE: Do not manually edit this file. It has been autogenerated by
 * protocol/parse.py. Any changes should me made there, instead of here.
 */
#pragma once
#include <boost/cstdint.hpp>
#include <cockpit/packet/Packet.h>
#include <cockpit/packet/Parameters.h>

namespace cockpit {
namespace packet {
namespace protocol {

// Npc Dead
class Quest_NPCDead : public Packet
{
private:
	packet::MUID uidKillerPlayer;
	packet::MUID uidNPC;

public:
	enum { packetID = 6004 };

	Quest_NPCDead(packet::MUID uidKillerPlayer, packet::MUID uidNPC);

	const char* name() const;
	const char* doc() const;
	boost::uint16_t id() const;
	Buffer serialize() const;

	~Quest_NPCDead()
	{
	}

};

}
}
}