/*
 * NOTICE: Do not manually edit this file. It has been autogenerated by
 * protocol/parse.py. Any changes should me made there, instead of here.
 */
#pragma once
#include <boost/cstdint.hpp>
#include <cockpit/packet/Packet.h>
#include <cockpit/packet/Parameters.h>

namespace cockpit {
namespace packet {
namespace protocol {

// Stage Go
class Stage_StageGo : public Packet
{
private:
	packet::uint32 RoomNo;

public:
	enum { packetID = 1331 };

	Stage_StageGo(const packet::uint32& RoomNo);

	const char* name() const;
	const char* doc() const;
	boost::uint16_t id() const;
	Buffer serialize() const;

	~Stage_StageGo()
	{
	}

};

}
}
}
