/*
 * NOTICE: Do not manually edit this file. It has been autogenerated by
 * protocol/parse.py. Any changes should me made there, instead of here.
 */
#pragma once
#include <boost/cstdint.hpp>
#include <cockpit/packet/Packet.h>
#include <cockpit/packet/Parameters.h>

namespace cockpit {
namespace packet {
namespace protocol {

// Response stage setting
class Stage_ResponseStageSetting : public Packet
{
private:
	packet::MUID uidStage;
	packet::blob StageSetting;
	packet::blob CharSetting;
	packet::int32 StageState;
	packet::MUID uidMaster;

public:
	enum { packetID = 1412 };

	Stage_ResponseStageSetting(packet::MUID uidStage, packet::blob StageSetting, packet::blob CharSetting, packet::int32 StageState, packet::MUID uidMaster);

	const char* name() const;
	const char* doc() const;
	boost::uint16_t id() const;
	Buffer serialize() const;

	~Stage_ResponseStageSetting()
	{
	}

};

}
}
}