/*
 * NOTICE: Do not manually edit this file. It has been autogenerated by
 * protocol/parse.py. Any changes should me made there, instead of here.
 */
#pragma once
#include <boost/cstdint.hpp>
#include <cockpit/packet/Packet.h>
#include <cockpit/packet/Parameters.h>

namespace cockpit {
namespace packet {
namespace protocol {

// Stage Request QuickJoin
class Stage_RequestQuickJoin : public Packet
{
private:
	packet::MUID uidPlayer;
	packet::blob Param;

public:
	enum { packetID = 1322 };

	Stage_RequestQuickJoin(const packet::MUID& uidPlayer, const packet::blob& Param);

	const char* name() const;
	const char* doc() const;
	boost::uint16_t id() const;
	Buffer serialize() const;

	~Stage_RequestQuickJoin()
	{
	}

};

}
}
}
