/*
 * NOTICE: Do not manually edit this file. It has been autogenerated by
 * protocol/parse.py. Any changes should me made there, instead of here.
 */
#pragma once
#include <boost/cstdint.hpp>
#include <cockpit/packet/Packet.h>
#include <cockpit/packet/Parameters.h>

namespace cockpit {
namespace packet {
namespace protocol {

// Response peer list
class Stage_ResponsePeerList : public Packet
{
private:
	packet::MUID uidStage;
	packet::blob PeerList;

public:
	enum { packetID = 1462 };

	Stage_ResponsePeerList(const packet::MUID& uidStage, const packet::blob& PeerList);

	const char* name() const;
	const char* doc() const;
	boost::uint16_t id() const;
	Buffer serialize() const;

	~Stage_ResponsePeerList()
	{
	}

};

}
}
}
