/*
 * NOTICE: Do not manually edit this file. It has been autogenerated by
 * protocol/parse.py. Any changes should me made there, instead of here.
 */
#pragma once
#include <boost/cstdint.hpp>
#include <cockpit/packet/Packet.h>
#include <cockpit/packet/Parameters.h>

namespace cockpit {
namespace packet {
namespace protocol {

// Update Round Finished Info
class Stage_RoundFinishInfo : public Packet
{
private:
	packet::MUID uidStage;
	packet::MUID uidChar;
	packet::blob PeerInfo;
	packet::blob KillInfo;

public:
	enum { packetID = 1502 };

	Stage_RoundFinishInfo(const packet::MUID& uidStage, const packet::MUID& uidChar, const packet::blob& PeerInfo, const packet::blob& KillInfo);

	const char* name() const;
	const char* doc() const;
	boost::uint16_t id() const;
	Buffer serialize() const;

	~Stage_RoundFinishInfo()
	{
	}

};

}
}
}
