/*
 * NOTICE: Do not manually edit this file. It has been autogenerated by
 * protocol/parse.py. Any changes should me made there, instead of here.
 */
#pragma once
#include <boost/cstdint.hpp>
#include <cockpit/packet/Packet.h>
#include <cockpit/packet/Parameters.h>

namespace cockpit {
namespace packet {
namespace protocol {

// Stage List
class Stage_List : public Packet
{
private:
	packet::int8 PrevStageListCount;
	packet::int8 NextStageListCount;
	packet::blob StageList;

public:
	enum { packetID = 1314 };

	Stage_List(packet::int8 PrevStageListCount, packet::int8 NextStageListCount, packet::blob StageList);

	const char* name() const;
	const char* doc() const;
	boost::uint16_t id() const;
	Buffer serialize() const;

	~Stage_List()
	{
	}

};

}
}
}
