/*
 * NOTICE: Do not manually edit this file. It has been autogenerated by
 * protocol/parse.py. Any changes should me made there, instead of here.
 */
#pragma once
#include <boost/cstdint.hpp>
#include <util/buffer.h>

namespace packet {
namespace protocol {
	class Packet
	{
	public:
		virtual const char* name() const = 0;
		virtual const char* docstring() const = 0;
		virtual boost::uint16_t id() const = 0;
		virtual Buffer serialize() const = 0;

		virtual ~Packet()
		{
		}
	};
}
}